server.port: 9090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: ci,test,default

logging.level.ru.practicum.ewmstat: TRACE
