DROP TABLE IF EXISTS endpoint_hit;

CREATE TABLE endpoint_hit (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	app varchar(255) NULL,
	uri varchar(1000) NULL,
	ip varchar(255) NULL,
	hit_timestamp timestamp NOT NULL,
	CONSTRAINT endpoint_hit_pkey PRIMARY KEY (id)
);