DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS events_compilations;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS categories;

CREATE TABLE users (
	id      int8            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email   varchar(255)    NOT NULL UNIQUE,
	name    varchar(255)    NOT NULL
);

CREATE TABLE compilations (
	id      int8            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title   varchar(255)    NOT NULL UNIQUE,
	pinned  bool            NULL
);

CREATE TABLE categories (
	id      int8            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name"  varchar(255)    NOT NULL UNIQUE
);

CREATE TABLE events (
	id                  int8            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation          varchar(2000)   NULL,
	confirmed_requests  int4            NOT NULL,
	created_on          timestamp       NULL,
	description         varchar(7000)   NULL,
	event_date          timestamp       NULL,
	paid                bool            NULL,
	participant_limit   int4            NULL,
	available           bool            NULL,
	published_on        timestamp       NULL,
	request_moderation  bool            NULL,
	state               int4            NULL,
	title               varchar(120)    NULL,
	"views"             int4            NOT NULL,
	category_id         int8            NULL REFERENCES categories (id),
	initiator_id        int8            NULL REFERENCES users (id),
	latitude            float4          NOT NULL,
	longitude           float4          NOT NULL
);

CREATE TABLE events_compilations (
	event_id        int8 NOT NULL REFERENCES events (id),
	compilation_id  int8 NOT NULL REFERENCES compilations (id),
	CONSTRAINT events_compilations_pkey PRIMARY KEY (event_id, compilation_id)
);

CREATE TABLE requests (
	id              int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created         timestamp   NOT NULL,
	event_id        int8        NULL REFERENCES events (id),
	requester_id    int8        NULL REFERENCES users (id),
	state           int4        NULL,
	CONSTRAINT requests_unique UNIQUE (event_id, requester_id)
);

CREATE TABLE comments (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"text" varchar(7000) NULL,
	created_on timestamp NOT NULL,
	author_id int8 NOT NULL REFERENCES users (id),
	is_evidence bool NOT NULL,
	event_id int8 NOT NULL REFERENCES events (id),
	is_modified bool NOT NULL,
	last_modified_on timestamp NULL,
	state int4 NOT NULL
);